# THIS FILE IS FOR DEVELOPMENT PURPOSES ONLY
# DO NOT USE IT IN PRODUCTION

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dsek
      POSTGRES_DB: dsek
      POSTGRES_PASSWORD: dsek
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - .dev/db/dumps:/dumps
    networks:
      - primary

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile.development
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: dsek
      DATABASE_USERNAME: dsek
      DATABASE_PASSWORD: dsek
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      APP_KEYS: secret
      API_TOKEN_SALT: secret
      ADMIN_JWT_SECRET: secret
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - primary
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    environment:
      STRAPI_BASE_URL: "http://strapi:1337"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - primary
    depends_on:
      - strapi

volumes:
  db:
    name: dsek-dev-db

networks:
  primary:
